backend: { name: git-gateway, branch: main }
local_backend: true
locale: es
media_folder: _static/images/uploads
collections:
  - label: Configuración
    name: files
    editor: { preview: false }
    files:
      - label: '⚙️ Settings'
        name: settings
        file: _data/settings.yaml
        fields:
          - { label: 'HTML Lang', name: lang, widget: string }
          - { label: 'URL Base', name: url, widget: string }
          - { label: Titulo, name: title, widget: string }
          - { label: Descripción, name: description, widget: string }
          - { label: 'Open Graph', name: og, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: E-Mail, name: email, widget: string }
          - { label: Instagram, name: instagram, widget: string }