backend: { name: git-gateway, branch: main }
local_backend: true
locale: 'es'
media_folder: 'static/images/uploads'
collections:
  - label: Configuracion
    name: files
    editor: { preview: false }
    files:
      - label: '🎠 Carousel'
        name: carousel
        file: data/carousel.json
        media_folder: '/static/images/carousel'
        fields:
          - label: Slides
            name: slides
            label_singular: slide
            widget: list
            allow_add: true
            fields:
              - label: Logo
                name: logo
                widget: list
                allow_add: true
                summary: '{{fields.titulo}}'
                fields:
                  - { label: Titulo, name: titulo, widget: string }
                  - { label: URL, name: url, widget: string, required: false }
                  - {
                      label: 'Imagen [320x287] (playlist-<genero>.jpg)',
                      name: imagen,
                      widget: image,
                    }
      - label: '🔖 Playlists'
        name: playlists
        file: data/playlists.json
        media_folder: '/static/images/playlists'
        fields:
          - label: Playlists
            name: playlists
            widget: list
            allow_add: true
            fields:
              - { label: Titulo, name: titulo, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: 'Imagen [320x287] (playlist-<genero>.jpg)', name: imagen, widget: image }
      - label: '📻 Programación'
        name: programacion
        file: data/programacion.json
        media_folder: '/static/images/programacion'
        fields:
          - { label: Esconder?, name: invisible, widget: boolean, required: false }
          - label: Programación
            name: programacion
            widget: list
            allow_add: true
            fields:
              - { label: Titulo, name: titulo, widget: string }
              - { label: Esconder?, name: invisible, widget: boolean, required: false }
              - label: Episodios
                name: episodios
                widget: list
                fields:
                  - { label: Titulo, name: title, widget: string }
                  - { label: URL, name: url, widget: string }
                  - {
                      label: Fecha,
                      name: fecha,
                      widget: datetime,
                      format: 'DD-MM-YYYY',
                      date_format: 'DD-MM-YYYY',
                      time_format: false,
                    }
              - { label: Imagen, name: imagen, widget: image }
              - { label: Dia, name: dia, widget: string }
              - { label: Horario, name: hora, widget: string }
              - { label: Tags, name: tags, widget: list }
              - { label: Descripcion, name: descripcion, widget: 'markdown' }
              - { label: Musicalizacion, name: musicalizacion, widget: string }
              - { label: Contacto, name: contacto, widget: string }
      - label: '🎥 Audiovisual'
        name: audiovisual
        file: data/audiovisual.json
        fields:
          - label: Audiovisual
            name: audiovisual
            widget: list
            allow_add: true
            fields:
              - { label: Titulo, name: titulo, widget: string }
              - { label: Logo, name: logo, widget: image, media_folder: '/static/images/logos' }
              - {
                  label: 'Es un background claro?',
                  name: isBgLight,
                  widget: boolean,
                  required: true,
                }
              - {
                  label: Background,
                  name: background,
                  widget: image,
                  media_folder: '/static/images/backgrounds',
                }
              - { label: Descripcion, name: descripcion, widget: 'markdown' }
              - {
                  label: Imagen,
                  name: imagen,
                  widget: image,
                  media_folder: '/static/images/flyers',
                }
              - {
                  label: Plataforma,
                  name: plataforma,
                  widget: select,
                  options: ['instagram', 'youtube'],
                }
              - { label: 'Texto del Link', name: url-texto, widget: string }
              - { label: URL, name: url, widget: string }
      - label: '📚 Editorial'
        name: editorial
        file: data/editorial.json
        media_folder: '/static/images/editorial'
        fields:
          - label: Editorial
            name: editorial
            widget: list
            allow_add: true
            fields:
              - { label: Titulo, name: titulo, widget: string }
              - { label: Subtitulo, name: subtitulo, widget: markdown }
              - { label: Imagen, name: imagen, widget: image }
              - { label: Precio, name: precio, widget: number }
              - { label: Agotado?, name: agotado, widget: boolean, required: false }
              - { label: URL, name: url, widget: string }
              - { label: Descripcion, name: descripcion, widget: markdown }
      - label: '🤝 Encuentros'
        name: encuentros
        file: data/encuentros.json
        fields:
          - label: Encuentros
            name: encuentros
            widget: list
            allow_add: true
            fields:
              - { label: Titulo, name: titulo, widget: string }
              - { label: Logo, name: logo, widget: image, media_folder: '/static/images/logos' }
              - {
                  label: 'Es un background claro?',
                  name: isBgLight,
                  widget: boolean,
                  required: true,
                }
              - {
                  label: Background,
                  name: background,
                  widget: image,
                  media_folder: '/static/images/backgrounds',
                }
              - { label: Descripcion, name: descripcion, widget: 'markdown' }
              - {
                  label: Imagen,
                  name: imagen,
                  widget: image,
                  media_folder: '/static/images/flyers',
                }
              - {
                  label: Plataforma,
                  name: plataforma,
                  widget: select,
                  options: ['instagram', 'youtube'],
                }
              - { label: 'Texto del Link', name: url-texto, widget: string }
              - { label: URL, name: url, widget: string }
      - label: '⚙️ Settings'
        name: settings
        file: data/settings.yaml
        fields:
          - { label: URL, name: url, widget: string }
          - { label: Titulo, name: title, widget: string }
          - { label: Descripcion, name: description, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: 'Open Graph', name: image, widget: string }
          - { label: 'App Store', name: app-store, widget: string }
          - { label: 'Google Play', name: google-play, widget: string }
          - { label: Youtube, name: youtube, widget: string }
          - { label: Facebook, name: facebook, widget: string }
          - { label: Instagram, name: instagram, widget: string }
          - { label: Spotify, name: spotify, widget: string }
          - { label: E-Mail, name: email, widget: string }
  - label: Novedades
    name: noticias
    folder: pages/p
    create: true
    editor: { preview: false }
    summary: '{{day}}/{{month}}/{{year}} {{hour}}:{{minute}} - {{fields.title}}'
    # identifier_field: date
    slug: '{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}'
    # slug: '{{year}}{{month}}{{day}}-{{slug}}'
    fields:
      - { label: Titulo, name: title, widget: string }
      - { label: Fecha, name: date, widget: datetime }
      - widget: select
        label: 'tags'
        name: 'tags'
        multiple: true
        create: true
        options: ['noticias', 'fanzines', 'eventos', 'encuentros', 'talleres']
      - { label: 'Texto', name: 'body', widget: 'markdown' }
      - { label: 'Imagen', name: image, widget: image }