_:
  email: unfueguito@gmail.com
  tienda: https://tintalibre.com.ar/book/1363/Si_no_te_inspira,_no_es
  stickers: https://www.dropbox.com/scl/fo/2tqzh2bntiu3vhipulwju/h?dl=0&rlkey=2g26hcttmvtyo1i9yd7uo5ilr
seo:
  lang: es-AR
  url: https://sinoteinspiranoes.com
  title: Si no te inspira no es
  description: Próximamente
  og: https://sinoteinspiranoes.com/static/images/og.png
  author: '@unfueguito'
nav:
  - title: Inicio
    url: '/'
  - title: Tienda
    url: 'https://tintalibre.com.ar/book/1363/Si_no_te_inspira,_no_es'
    external: true
  - title: Stickers
    url: 'https://www.dropbox.com/scl/fo/2tqzh2bntiu3vhipulwju/h?dl=0&rlkey=2g26hcttmvtyo1i9yd7uo5ilr'
  - title: Comentarios
    url: '/comentarios'
  - title: Contacto
    url: '/contacto'
social:
  - title: Youtube
    icon: youtube
    url: https://youtube.com/@sinoteinspiranoes
  - title: Twitter
    icon: twitter
    url: https://twitter.com/unfueguito
  - title: Instagram
    icon: instagram
    url: https://instagram.com/unfueguito
  - title: Facebook
    icon: facebook
    url: https://www.facebook.com/unFueguito/
  - title: Tiktok
    icon: tiktok
    url: http://www.tiktok.com/@unfueguito

# helpers
stickers:
  - benditos
  - calma
  - CH
  - DIVER
  - inspira
  - mate
  - me voy
  - mesurass
  - muy bien
  - no queres
  - noter
  - olvidam