lang: es-AR
url: https://sinoteinspiranoes.com
title: Si no te inspira no es
description: Próximamente
og: https://sinoteinspiranoes.com/static/images/og.png
author: '@unfueguito'
email: unfueguito@gmail.com
instagram: https://www.instagram.com/unfueguito